{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "99db3af9-4ecc-4a3b-be9d-f6295c24f7a9",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import joblib\n",
    "import os\n",
    "\n",
    "st.set_page_config(\n",
    "    page_title=\"SmartCare Underwriting Engine\",\n",
    "    page_icon=\"🛡️\",\n",
    "    layout=\"wide\",\n",
    "    initial_sidebar_state=\"expanded\"\n",
    ")\n",
    "\n",
    "st.markdown(\"\"\"\n",
    "    <style>\n",
    "    .main-header { font-size: 2.2rem; font-weight: 700; color: #1E293B; margin-bottom: 0.25rem; }\n",
    "    .sub-header { font-size: 1.05rem; color: #64748B; margin-bottom: 2rem; }\n",
    "    .card-container { background-color: #F8FAFC; border: 1px solid #E2E8F0; padding: 1.5rem; border-radius: 0.75rem; margin-bottom: 1rem; }\n",
    "    .metric-box { background-color: #EFF6FF; border: 1px solid #BFDBFE; padding: 1.5rem; border-radius: 0.75rem; text-align: center; }\n",
    "    .metric-label { font-size: 0.95rem; font-weight: 600; color: #1E40AF; text-transform: uppercase; letter-spacing: 0.05em; }\n",
    "    .metric-value { font-size: 2.4rem; font-weight: 800; color: #1E3A8A; margin-top: 0.25rem; }\n",
    "    </style>\n",
    "\"\"\", unsafe_allow_html=True)\n",
    "\n",
    "@st.cache_resource\n",
    "def load_underwriting_model():\n",
    "    model_path = 'health_insurance_model.pkl'\n",
    "    if os.path.exists(model_path):\n",
    "        return joblib.load(model_path)\n",
    "    return None\n",
    "\n",
    "pipeline = load_underwriting_model()\n",
    "\n",
    "with st.sidebar:\n",
    "    st.image(\"https://img.icons8.com/external-flatart-icons-flat-flatarticons/128/external-shield-medical-health-care-flatart-icons-flat-flatarticons.png\", width=60)\n",
    "    st.markdown(\"### **Risk Parameters**\")\n",
    "    st.caption(\"Adjust core biographical metrics to evaluate premium risk variance live.\")\n",
    "    st.markdown(\"---\")\n",
    "    \n",
    "    age = st.slider(\"Primary Applicant Age\", min_value=18, max_value=100, value=35, step=1)\n",
    "    weight = st.number_input(\"Weight (kg)\", min_value=30.0, max_value=250.0, value=72.5, step=0.5)\n",
    "    bmi = st.number_input(\"Calculated BMI\", min_value=10.0, max_value=60.0, value=24.2, step=0.1)\n",
    "    bloodpressure = st.slider(\"Systolic Blood Pressure\", min_value=80, max_value=200, value=120, step=1)\n",
    "    no_of_dependents = st.number_input(\"Dependents Scheduled\", min_value=0, max_value=10, value=0, step=1)\n",
    "    \n",
    "    st.markdown(\"---\")\n",
    "    city = st.selectbox(\"Geographic Rating Area (City)\", options=['NewYork', 'Boston', 'Phildelphia', 'Pittsburg', 'Buffalo', 'AtlanticCity', 'Portland', 'Cambridge', 'Hartford', 'Springfield', 'Brimingham', 'Charleston', 'Charlotte', 'Louisville', 'Memphis', 'Nashville', 'NewOrleans'])\n",
    "\n",
    "st.markdown('<div class=\"main-header\">SmartCare Underwriting Risk Interface</div>', unsafe_allow_html=True)\n",
    "st.markdown('<div class=\"sub-header\">Automated cost prediction engine built using historical health claim models.</div>', unsafe_allow_html=True)\n",
    "\n",
    "if pipeline is None:\n",
    "    st.error(\"🚨 Core engine pipeline file (`health_insurance_model.pkl`) not found in the current directory. Please make sure to run your training notebook/script to save the model artifact first.\")\n",
    "else:\n",
    "    col1, col2 = st.columns([5, 4], gap=\"large\")\n",
    "    \n",
    "    with col1:\n",
    "        st.markdown('<div class=\"card-container\">', unsafe_allow_html=True)\n",
    "        st.markdown(\"#### **Clinical & Behavioral Profile**\")\n",
    "        st.markdown(\"<br>\", unsafe_allow_html=True)\n",
    "        \n",
    "        sub_c1, sub_c2, sub_c3 = st.columns(3)\n",
    "        with sub_c1:\n",
    "            smoker_input = st.toggle(\"Nicotine/Smoker\", value=False)\n",
    "        with sub_c2:\n",
    "            diabetes_input = st.toggle(\"Diagnosed Diabetes\", value=False)\n",
    "        with sub_c3:\n",
    "            exercise_input = st.toggle(\"Regular Exercise\", value=True)\n",
    "            \n",
    "        st.markdown(\"<br>\", unsafe_allow_html=True)\n",
    "        has_hereditary = st.selectbox(\"Genetic / Hereditary Status\", options=[\"No Stated Hereditary History\", \"Known Hereditary Condition History\"])\n",
    "        st.markdown('</div>', unsafe_allow_html=True)\n",
    "\n",
    "        st.markdown('<div class=\"card-container\">', unsafe_allow_html=True)\n",
    "        st.markdown(\"#### **Occupational Demographics**\")\n",
    "        job_category = st.selectbox(\"Professional Domain Cluster\", options=['Office', 'Technical', 'Medical', 'Service', 'Creative', 'Other'])\n",
    "        \n",
    "        if bmi < 18.5: bmi_grouping = 'Underweight'\n",
    "        elif bmi < 25: bmi_grouping = 'Healthy'\n",
    "        elif bmi < 30: bmi_grouping = 'Overweight'\n",
    "        else: bmi_grouping = 'Obese'\n",
    "            \n",
    "        st.markdown(f\"**Automated Segment Mapping:** `{bmi_grouping}`\")\n",
    "        st.markdown('</div>', unsafe_allow_html=True)\n",
    "\n",
    "    with col2:\n",
    "        st.markdown(\"#### **Analysis & Premium Valuation**\")\n",
    "        st.caption(\"Click below to pass inputs into the Random Forest Regressor framework.\")\n",
    "        \n",
    "        smoker = 1.0 if smoker_input else 0.0\n",
    "        diabetes = 1.0 if diabetes_input else 0.0\n",
    "        regular_ex = 1.0 if exercise_input else 0.0\n",
    "        has_hereditary_disease = 1.0 if has_hereditary == \"Known Hereditary Condition History\" else 0.0\n",
    "        smoker_age_risk = smoker * age\n",
    "        \n",
    "        user_payload = pd.DataFrame([{\n",
    "            'age': float(age), 'sex': 'male', 'weight': float(weight), 'bmi': float(bmi),\n",
    "            'no_of_dependents': float(no_of_dependents), 'smoker': smoker, 'city': city,\n",
    "            'bloodpressure': float(bloodpressure), 'diabetes': diabetes, 'regular_ex': regular_ex,\n",
    "            'smoker_age_risk': smoker_age_risk, 'has_hereditary_disease': has_hereditary_disease,\n",
    "            'bmi_grouping': bmi_grouping, 'job_category': job_category\n",
    "        }])\n",
    "        \n",
    "        st.markdown(\"<br>\", unsafe_allow_html=True)\n",
    "        \n",
    "        if st.button(\"Calculate Expected Insurance Claim\", type=\"primary\", use_container_width=True):\n",
    "            predicted_claim = pipeline.predict(user_payload)[0]\n",
    "            \n",
    "            st.markdown(f\"\"\"\n",
    "                <div class=\"metric-box\">\n",
    "                    <div class=\"metric-label\">Predicted Annual Cost Valuation</div>\n",
    "                    <div class=\"metric-value\">${predicted_claim:,.2f}</div>\n",
    "                </div>\n",
    "            \"\"\", unsafe_allow_html=True)\n",
    "            \n",
    "            st.markdown(\"<br>\", unsafe_allow_html=True)\n",
    "            st.info(\"💡 **Underwriting Note:** This output represents the model's localized mean regression baseline score. Actual policy quotes may vary based on structural market adjustments.\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
